### ISSUE TITLE
WebSphere Cartridge for windows

### ISSUE THREAD

**Issue by EktaC** [juhoffma/openshift-origin-websphere-cartridge#1]
I need to deploy the websphere cartridge on winnode and not on linux. I have installed the server and was service is running but there are issues in deploying the cartridge as the entire control, setup files are made in linux. Do we have its windows versions available? Please help. I need this on priority.

**Comment by sebastianfaulhaber** [comment]
Hi,

this cartridge is currently only supported on Linux. I am sorry to say that there are no plans to make this work under Windows based OpenShift Nodes.

Regards,
Sebastian
